title = "Per organisation configuration file"

[organisations]

[organisations.acme.platform.elastic]

kibana_workspace_name = "ACME"
query_language = "esql"

[organisations.acme.platform.elastic.logs.azure]

indexes = ["logs-azure-*-acme"]

[organisations.acme.platform.elastic.logs.cloudtrail]

indexes = ["logs-aws.cloudtrail-*-acme"]


[organisations.ecorp.platform.splunk]

[organisations.ecorp.platform.splunk.logs.cloudtrail]

indexes = ["cloudtrail"]