
title = "This is generic configuration for each SIEM platform. It is treated as default configuration and is overwritten if alernative config is specified in organisations.toml"

[platforms]

[platforms.elastic]

username = "elastic"
password = "changeme"

kibana_base_url = "https://192.168.86.108:5601"
kibana_workspace_name = "Default"
elasticsearch_hosts = [
    "https://192.168.86.108:9200"
]

ssl_verify = false

schedule_interval = 5
schedule_interval_unit = "m"
query_language = "esql"

[platforms.elastic.logs.cloudtrail]

# The separation of query_pipelines and pipelines is to allow for the use of a query pipeline for the initial query (primarily for pre-compilation testing) and then a pipeline for the subsequent processing of the data most often to format the output into a useable detection by the output platform (Elastic, Splunk, Sentinel, etc).
query_pipelines = ["pipelines/elastic/aws/ecs_cloudtrail.yml"]
pipelines = ["pipelines/elastic/aws/esql_ndjson_cloudtrail.yml"]
product = "cloudtrail"
indexes = ["logs-aws.cloudtrail"]

[platforms.elastic.logs.azure]

query_pipelines = []
pipelines = ["pipelines/elastic/aws/esql_ndjson_cloudtrail.yml"]
product = "azure"
indexes = ["logs-azure"]

[platforms.splunk]

query_language = "splunk"
ssl_verify = false
username = "admin"
password = "dontchangeme"
host = "192.168.86.106"
port = 8089


[platforms.splunk.logs.cloudtrail]

query_pipelines = []
pipelines = []
product = "cloudtrail"
indexes = ["cloudtrail"]

# [platforms.sentinel]

# query_language = "kusto"